# ----------------------
# Paramètres de base du site
# ----------------------
locale                   : "en-US"
site_theme               : "default"
title                    : "Iliès Chenene"
title_separator          : "-"
name                     : &name "Iliès Chenene"
description              : &description "Master’s student in Mathematics & AI at Université Paris-Saclay"
url                      : "https://i-chenene.github.io"
baseurl                  : ""
repository               : "i-chenene/i-chenene.github.io"

# ----------------------
# Auteur
# ----------------------
author:
  avatar           : "profile.png"
  name             : "Iliès Chenene"
  bio              : "M1 Mathematics & AI @ Université Paris-Saclay"
  location         : "Gif-sur-Yvette, France"
  email            : "ilies.chenene@universite-paris-saclay.fr"

  # Liens dev
  github           : "i-chenene"
  kaggle           : 
  stackoverflow    : 

  navbar:
  enable: true
  links:
    - title: "Projects"
      url: /projects/
    - title: "CV"
      url: /cv/

  # Réseaux
  linkedin         : "ilieschenene"
  twitter          : 

# ----------------------
# Catégories de publications (si jamais tu ajoutes plus tard)
# ----------------------
publication_category:
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# ----------------------
# Réglages du site
# ----------------------
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false

comments:
  provider               : false

atom_feed:
  hide                   : false

# ----------------------
# SEO & Social
# ----------------------
og_image                 : "profile.png"
og_description           : "Portfolio of Iliès Chenene — Mathematics & AI student at Paris-Saclay, aspiring Data Scientist."
social:
  type                   : Person
  name                   : "Iliès Chenene"
  links:
    - "https://github.com/i-chenene"
    - "https://www.linkedin.com/in/ilieschenene/"

# ----------------------
# Analytics (désactivé pour l’instant)
# ----------------------
analytics:
  provider               : false

# ----------------------
# Fichiers pris en compte
# ----------------------
include:
  - .htaccess
  - _pages
  - files

exclude:
  - node_modules
  - vendor

# ----------------------
# Markdown / Rendu
# ----------------------
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true

# ----------------------
# Collections utiles
# ----------------------
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  cv:
    output: true
    permalink: /:collection/:path/

# ----------------------
# Valeurs par défaut
# ----------------------
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# ----------------------
# SASS / CSS
# ----------------------
sass:
  sass_dir: _sass
  style: compressed

# ----------------------
# Plugins GitHub Pages compatibles
# ----------------------
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

# ----------------------
# Archives / Tags
# ----------------------
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# ----------------------
# Compression HTML
# ----------------------
compress_html:
  clippings: all
  ignore:
    envs: development
